version: '3.4'

services:
  accountservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  inventoryservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  shoppingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  store2018:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

